# Generated by Django 5.0 on 2023-12-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosuct',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
